# R Script to Parse Binary Data from Teensy Data Logger
#
# This script reads the custom binary format generated by the C++ code
# in the 'arduino_logger_revised_gps' artifact.

# Required libraries (install if you don't have them)
# install.packages("tidyverse") # Optional, but recommended for data manipulation
library(tidyverse)
library(ggplot2)

# --- Main Parsing Function ---

# Prompt user to select the binary file
file_path <- file.choose()

{
  if (!file.exists(file_path)) {
    stop("File not found.")
  }
  
  # Open the file for reading in binary mode
  con <- file(file_path, "rb")
  
  # Create a list to hold the parsed records
  records_list <- list()
  
  # Loop until the end of the file is reached
  while (TRUE) {
    
    DegSamples <- readBin(con, integer(), n = 1, size = 4)
    if (length(DegSamples) == 0) {
      break # End of file
    }
    # 3. Read the DegTimeArray based on the value of hzSamples
    # Use max(0, hzSamples) to prevent errors if hzSamples is negative or invalid
    DegTimeArray <- list(readBin(con, integer(), n = max(0, 18), size = 4))
    DegSumTime <- sum(unlist(DegTimeArray))
    
    HallSamples <- readBin(con, integer(), n = 1, size = 4)
    HallTimeArray <- list(readBin(con, integer(), n = max(0, HallSamples), size = 4))
    HallSumTime <- sum(unlist(HallTimeArray))
    
    HallSamples2 <- readBin(con, integer(), n = 1, size = 4)
    HallTimeArray2 <- list(readBin(con, integer(), n = max(0, HallSamples2), size = 4))
    HallSumTime2 <- sum(unlist(HallTimeArray2))
    
    # 7. Assemble the full record and add it to our list
    record <- list(
      DegSumTime = DegSumTime,
      DegSamples = DegSamples,
      DegTimeArray = DegTimeArray,
      HallSumTime = HallSumTime,
      HallSamples = HallSamples,
      HallTimeArray = HallTimeArray,
      HallSumTime2 = HallSumTime2,
      HallSamples2 = HallSamples2,
      HallTimeArray2 = HallTimeArray2
    )
    
    records_list[[length(records_list) + 1]] <- record
  }
  
  # Close the file connection
  close(con)
  
  # Use bind_rows to create the final tibble
  if(length(records_list) > 0) {
    log_data <- bind_rows(records_list)
  }
}

#early code when first sample was not 18
#log_data <- log_data[-1,]

# --- Define Constants ---
WHEEL_CIRCUMFERENCE_M <- 2.15
SAMPLES_PER_REV <- 18
CONVERSION_FACTOR_KMH <- (WHEEL_CIRCUMFERENCE_M / SAMPLES_PER_REV) * 1000000 * 3.6
CONVERSION_FACTOR_REVOLUTION <- WHEEL_CIRCUMFERENCE_M * 1000000 * 3.6


# --- Main Conversion and Comparison Code ---
speed_comparison_data <- log_data %>%
  # Add a row number to serve as a unique ID for each record
  mutate(record_id = row_number()) %>%
  
  # 1. Convert time arrays to speed (km/h) arrays
  mutate(
    # Use map() to apply the conversion formula to each element of the time arrays
    DegSpeed_kmh = map(DegTimeArray, ~ CONVERSION_FACTOR_KMH / unlist(.x)),
    HallSpeed_kmh = map(HallTimeArray, ~ CONVERSION_FACTOR_KMH / unlist(.x)),
    HallSpeed2_kmh = map(HallTimeArray2, ~ CONVERSION_FACTOR_KMH / unlist(.x))
  ) %>%
  
  # 2. Compare the two new speed arrays
  mutate(
    length_diff = map_int(DegSpeed_kmh, length) - map_int(HallSpeed_kmh, length),
    
    # Calculate the speed difference array (in km/h)
    speed_diff_array = map2(DegSpeed_kmh, HallSpeed_kmh, ~ {
      if (length(.x) != length(.y)) {
        return(NA_real_)
      }
      .x - .y
    }),
    
    # Create summary columns for the speed difference
    max_abs_speed_diff = map_dbl(speed_diff_array, ~if(all(is.na(.x))) NA else max(abs(.x))),
    mean_abs_speed_diff = map_dbl(speed_diff_array, ~if(all(is.na(.x))) NA else mean(abs(.x)))
  )

speed_comparison_data$DegSpeed_kmh[34]
speed_comparison_data$HallSpeed_kmh[34]
speed_comparison_data$HallSpeed2_kmh[34]
# --- Analyzing the Results ---

# View the new tibble with the speed and difference columns
print(speed_comparison_data)

# Find rows with a maximum speed difference greater than a threshold (e.g., 0.5 km/h)
SPEED_THRESHOLD_KMH <- 0.5
large_speed_diffs <- speed_comparison_data %>%
  filter(max_abs_speed_diff > SPEED_THRESHOLD_KMH)

cat(paste("\n--- Records with a Maximum Speed Difference >", SPEED_THRESHOLD_KMH, "km/h ---\n"))
print(large_speed_diffs)
large_speed_diffs$HallTimeArray[176]
large_speed_diffs$DegTimeArray[176]

# --- 3. Prepare Data for Plotting ---

speed_plot_data <- speed_comparison_data %>%
  select(record_id, speed_diff_array) %>%
  filter(!sapply(speed_diff_array, function(x) all(is.na(x)))) %>%
  unnest(cols = c(speed_diff_array)) %>%
  group_by(record_id) %>%
  mutate(sample_number = row_number()) %>%
  ungroup()

# --- 4. Generate New Plots Based on Speed Difference ---

# Plot 1: Line plot for speed difference of every record
ggplot(speed_plot_data, aes(x = sample_number, y = speed_diff_array, group = record_id)) +
  geom_line(alpha = 0.1, color = "green") +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  labs(
    title = "Speed Difference vs. Sample Number for All Records",
    x = "Sample Number in Array",
    y = "Speed Difference (km/h)"
  ) +
  theme_minimal()

# Plot 2: Boxplot summary of speed differences
ggplot(speed_plot_data, aes(x = factor(sample_number), y = speed_diff_array)) +
  geom_boxplot(fill = "lightgreen", outlier.color = "orange", outlier.size = 1.5) +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  labs(
    title = "Distribution of Speed Differences by Sample Number",
    x = "Sample Number",
    y = "Speed Difference (km/h)"
  ) +
  theme_minimal()

# --- 1. Calculate Per-Revolution Speed and Difference ---
rev_speed_data <- log_data %>%
  # Handle potential cases where SumTime might be zero to avoid infinite speeds
  filter(DegSumTime > 0 & HallSumTime > 0) %>%
  mutate(
    # Convert the total time for one revolution into an average speed in km/h
    DegSpeed_kmh = CONVERSION_FACTOR_REVOLUTION / DegSumTime,
    HallSpeed_kmh = CONVERSION_FACTOR_REVOLUTION / HallSumTime,
    
    # Calculate the difference in the final speed calculation for this revolution
    RevSpeedDiff_kmh = DegSpeed_kmh - HallSpeed_kmh,
    
    # Add an ID for plotting trends over time
    revolution_id = row_number()
  )

# --- 2. Analyze the Results ---

# View the new data frame with per-revolution speeds
cat("--- Per-Revolution Speed Comparison ---\n")
print(rev_speed_data)

# Get a quick summary of the speed differences
cat("\n--- Summary of Speed Differences (km/h) ---\n")
summary(rev_speed_data$RevSpeedDiff_kmh)

# Filter for revolutions where the speed difference was notable (e.g., > 0.25 km/h)
SPEED_DIFF_THRESHOLD <- 0.25
large_rev_diffs <- rev_speed_data %>%
  filter(abs(RevSpeedDiff_kmh) > SPEED_DIFF_THRESHOLD)

cat(paste("\n--- Revolutions with Speed Difference >", SPEED_DIFF_THRESHOLD, "km/h ---\n"))
print(large_rev_diffs)


# --- 3. Visualize the Per-Revolution Differences 📊 ---

# Plot 1: Histogram to see the distribution of the speed difference
# This shows you how consistent the two measurements are overall.
ggplot(rev_speed_data, aes(x = RevSpeedDiff_kmh)) +
  geom_histogram(bins = 50, fill = "coral", color = "black", alpha = 0.8) +
  labs(
    title = "Distribution of Per-Revolution Speed Differences",
    subtitle = "Difference between speeds calculated from DegSumTime and HallSumTime",
    x = "Speed Difference (km/h)",
    y = "Number of Revolutions"
  ) +
  theme_minimal()

# Plot 2: Line plot to see if the difference changes over time
# This helps you spot trends, drifts, or periodic errors.
ggplot(rev_speed_data, aes(x = revolution_id, y = RevSpeedDiff_kmh)) +
  geom_line(color = "cyan4", alpha = 0.7) +
  geom_point(color = "cyan4", alpha = 0.5) +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  labs(
    title = "Speed Difference Over Time",
    x = "Revolution Number (Record Index)",
    y = "Speed Difference (km/h)"
  ) +
  theme_minimal()

write.table(apply(writeData,2,as.character), file="clipboard-16384", sep="\t", row.names=FALSE, col.names=T)




